---
title: "Week8_assignment"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 8 Assignment
# Problem 1
```{r}
library(ggplot2)
library(shiny)
library(dplyr)
library(DT)
grad <- read.csv("/Users/zongyangjiao/Desktop/DSO545_R/week7/recent_grads.csv")
```

```{r}
ui <- fluidPage(
  titlePanel(title = "Relationship between Characteristics of Different Categories of Majors"),
  sidebarLayout(
    sidebarPanel(
      helpText("This app is to describe relationship between share of women, unemployment rate, median income and total enrollment and help identify potential outliers."),
      selectInput(inputId = "x",
                  label = "Choose x variable",
                  choices = c("ShareWomen","Unemployment_rate","Median","Total"),
                  selected = "Unemployment_rate"),
      
      selectInput(inputId = "y",
                  label = "Choose y variable",
                  choices = c("ShareWomen","Unemployment_rate","Median","Total"),
                  selected = "Median")
    ),
    mainPanel(
      plotOutput(outputId = "plot", brush = "plot_brush"),
      dataTableOutput(outputId = "table")
    )
  )
)

server <- function(input, output){
  output$plot <- renderPlot({
    ggplot(grad, aes_string(x = input$x, y = input$y)) +
    geom_point() +
    theme_classic()
  })
  
  output$table <- DT::renderDataTable({
    brushedPoints(grad, brush = input$plot_brush) %>%
      select(Major_category, input$x, input$y, Total)
  })
}

shinyApp(ui = ui, server = server)
```

